# Generated by Django 5.1.2 on 2024-12-07 11:34

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0005_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=django_quill.fields.QuillField(blank=True, default='', max_length=250, null=True),
        ),
    ]
