# Generated by Django 5.1.2 on 2024-12-07 14:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0008_alter_orders_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
