# Generated by Django 5.1.2 on 2024-12-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_phone_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default='Endereço não especificado', max_length=15000),
        ),
    ]
