# Generated by Django 5.1.2 on 2024-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(blank=True, choices=[('01', 'Aveiro'), ('02', 'Beja'), ('03', 'Braga'), ('04', 'Bragança'), ('05', 'Castelo Branco'), ('06', 'Coimbra'), ('07', 'Évora'), ('08', 'Faro'), ('09', 'Guarda'), ('10', 'Leiria'), ('11', 'Lisboa'), ('12', 'Portalegre'), ('13', 'Porto'), ('14', 'Santarém'), ('15', 'Setúbal'), ('16', 'Viana do Castelo'), ('17', 'Vila Real'), ('18', 'Viseu'), ('20', 'Região Autónoma da Madeira'), ('30', 'Região Autónoma dos Açores')], max_length=200),
        ),
    ]
